#!/bin/bash
#   Copyright (C) 2015 Piotr Chmielnicki
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

INPUT="${1}"

if [ ! -f "${INPUT}" ]
then
    INPUT="$(zenity --file-selection --title='Select the file to decrypt'  --file-filter='*.enc')"
    if [ "$?" -ne 0 ]
    then
        exit 1
    fi
fi
if [ -z "`echo "${INPUT}" | grep '\.enc$'`" ]
then
    zenity --error --no-markup --title='Not a ciphertext' --text="${INPUT} is no a .enc file !" 
    exit 1
fi
OUTPUT=$(echo "${INPUT}" | sed 's/\.enc$//')
if [ -e "${OUTPUT}" ]
then
    if zenity --question --title='Warning' --text="${OUTPUT} exists. Do you want to Overwrite it ?"
    then
        rm -rf "${OUTPUT}"
    else
        exit 1
    fi
fi
if [ -z "${CRYPT0_HOME}" ]
then
    CRYPT0_HOME=~/.crypt0
fi
if [ -d "${CRYPT0_HOME}/peers" ]
then
    for DIR in "${CRYPT0_HOME}"/peers/*
    do
        decrypt0 "${INPUT}" "${DIR}"
        if [ "$?" -eq 0 ]
        then
            zenity --info --no-markup --title='Decryption succeded' --text="Decryption succeded from `basename "${DIR}"`"
            exit 0
        fi
    done
fi
PAD_DIR=$(zenity --file-selection --title='Directory containing pad' --directory)
if [ -z "${PAD_DIR}" ]
then
    exit 1
fi
OUT=$(decrypt0 "${INPUT}" "${PAD_DIR}" 2>&1)
if [ "$?" -ne 0 ]
then
    rm -f "${OUTPUT}"
    zenity --error --no-markup --title='Decryption failed' --text="${OUT}"
    exit 1
else
    if [ -z "${OUT}" ]
    then
        zenity --info --title='Decryption succeded' --text='Decryption succeded'
    else
        zenity --info --no-markup --title='Decryption succeded' --text="${OUT}" 
    fi
fi
